// lib/api/mock-data.ts
import {
  User,
  Task,
  DashboardStats,
  AgentStats,
  WeeklyTrend,
  ActivityItem,
  GeoPoint,
  Region,
  Notification,
  TaskStatsByExploitation,
  TaskStatsByZone,
  TaskStatsByCity,
  TaskStatsByRegion,
  ElectricRegion,
} from "./types";

// Mock Users
export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@minee.cm",
    firstName: "Jean-Pierre",
    lastName: "Nguema",
    company: "GROUPEMENT",
    role: "admin",
    phone: "+237 6 99 00 00 01",
    isActive: true,
    occupancyRate: 50,
    createdAt: "2026-01-15T08:00:00Z",
    lastLogin: "2026-03-26T09:30:00Z",
    tasksAssigned: 0,
    tasksCompleted: 0,
    status: 'en ligne'
  },
  {
    id: "2",
    email: "marie.ekotto@minee.cm",
    firstName: "Marie",
    lastName: "Ekotto",
    company: "GROUPEMENT",
    role: "team_lead",
    phone: "+237 6 99 00 00 02",
    isActive: true,
    createdAt: "2026-01-20T09:00:00Z",
    lastLogin: "2026-03-26T08:15:00Z",
    tasksAssigned: 48,
    occupancyRate: 90,
    tasksCompleted: 45,
    status: 'en ligne'
  },
  {
    id: "3",
    email: "paul.mvondo@minee.cm",
    firstName: "Paul",
    lastName: "Mvondo",
    company: "GROUPEMENT",
    role: "validation_agent",
    phone: "+237 6 99 00 00 03",
    isActive: true,
    createdAt: "2026-02-01T10:00:00Z",
    lastLogin: "2026-03-26T10:45:00Z",
    tasksAssigned: 125,
    tasksCompleted: 113,
    occupancyRate: 0,
    status: 'en ligne'
  },
  {
    id: "4",
    email: "agnes.fotso@minee.cm",
    firstName: "Agnès",
    lastName: "Fotso",
    company: "ENEO",
    role: "processing_agent",
    phone: "+237 6 99 00 00 04",
    isActive: true,
    createdAt: "2026-02-10T11:00:00Z",
    lastLogin: "2026-03-26T09:00:00Z",
    tasksAssigned: 90,
    tasksCompleted: 82,
    occupancyRate: 0,
    status: 'en ligne'
  },
  {
    id: "5",
    email: "olivier.nkono@minee.cm",
    firstName: "Olivier",
    lastName: "Nkono",
    company: "ENEO",
    role: "processing_agent",
    phone: "+237 6 99 00 00 05",
    isActive: true,
    createdAt: "2026-02-15T08:30:00Z",
    lastLogin: "2026-03-26T08:30:00Z",
    tasksAssigned: 98,
    occupancyRate: 0,
    tasksCompleted: 71,
    status: 'en ligne'
  },
  {
    id: "6",
    email: "sylvie.ateba@minee.cm",
    firstName: "Sylvie",
    lastName: "Ateba",
    company: "ENEO",
    role: "validation_agent",
    occupancyRate: 0,
    phone: "+237 6 99 00 00 06",
    isActive: true,
    createdAt: "2026-02-20T09:00:00Z",
    lastLogin: "2026-03-26T07:45:00Z",
    tasksAssigned: 55,
    tasksCompleted: 53,
    status: 'en ligne'
  },
];

// Mock Tasks - Mise à jour avec des tâches du 26 mars
export const mockTasks: Task[] = [
  {
    id: "task-001",
    type: "duplicate",
    status: "pending",
    priority: "high",
    title: "Doublon détecté - Compteur #A2345",
    description: "Deux entrées similaires trouvées pour le même emplacement",
    assignedTo: "4",
    createdAt: "2026-03-26T08:00:00Z",
    updatedAt: "2026-03-26T08:00:00Z",
    data: {
      koboId: "KBO-2345",
      eneoId: "ENEO-2345",
      location: "Yaoundé, Bastos",
    },
    sourceData: {
      id: "KBO-2345",
      name: "Compteur Résidentiel",
      address: "123 Rue Bastos",
      type: "Monophasé",
      power: "5kVA",
    },
    targetData: {
      id: "KBO-2346",
      name: "Compteur Résidentiel",
      address: "123 Rue de Bastos",
      type: "Monophasé",
      power: "5kVA",
    },
    similarity: 94,
    confidence: 87,
  },
  {
    id: "task-002",
    type: "difference",
    status: "in_progress",
    priority: "medium",
    title: "Différence Kobo/Eneo - Zone Bonanjo",
    description: "Données de puissance différentes entre les sources",
    assignedTo: "5",
    createdAt: "2026-03-26T09:30:00Z",
    updatedAt: "2026-03-26T10:15:00Z",
    data: {
      koboId: "KBO-5678",
      eneoId: "ENEO-5678",
      location: "Douala, Bonanjo",
      field: "power",
    },
    sourceData: {
      id: "KBO-5678",
      power: "10kVA",
      lastReading: "2026-03-25",
    },
    targetData: {
      id: "ENEO-5678",
      power: "15kVA",
      lastReading: "2026-03-24",
    },
  },
  {
    id: "task-003",
    type: "new_kobo",
    status: "completed",
    priority: "low",
    title: "Nouvelle entrée Kobo - Secteur 7",
    description: "Nouveau compteur enregistré via Kobo sans correspondance Eneo",
    assignedTo: "4",
    createdAt: "2026-03-26T07:00:00Z",
    updatedAt: "2026-03-26T09:30:00Z",
    completedAt: "2026-03-26T09:30:00Z",
    data: {
      koboId: "KBO-9012",
      location: "Yaoundé, Mvan",
    },
    sourceData: {
      id: "KBO-9012",
      name: "Nouveau Point de Livraison",
      address: "45 Avenue Mvan",
      type: "Triphasé",
      power: "20kVA",
      coordinates: { lat: 3.8480, lng: 11.5021 },
    },
  },
  {
    id: "task-004",
    type: "missing_eneo",
    status: "validated",
    priority: "high",
    title: "Données Eneo manquantes - Quartier Akwa",
    description: "Point référencé dans Eneo absent de Kobo",
    assignedTo: "5",
    createdAt: "2026-03-25T11:00:00Z",
    updatedAt: "2026-03-26T08:00:00Z",
    completedAt: "2026-03-25T16:00:00Z",
    validatedAt: "2026-03-26T08:00:00Z",
    validatedBy: "3",
    validationComment: "Données vérifiées sur le terrain",
    data: {
      eneoId: "ENEO-3456",
      location: "Douala, Akwa",
    },
    targetData: {
      id: "ENEO-3456",
      name: "Point Commercial",
      address: "78 Boulevard Akwa",
      type: "Triphasé",
      power: "50kVA",
    },
  },
  {
    id: "task-005",
    type: "duplicate",
    status: "pending",
    priority: "high",
    title: "Doublon détecté - Zone Mokolo",
    description: "Deux compteurs avec le même numéro de série",
    assignedTo: "4",
    createdAt: "2026-03-26T10:00:00Z",
    updatedAt: "2026-03-26T10:00:00Z",
    data: {
      koboId: "KBO-7891",
      eneoId: "ENEO-7891",
      location: "Yaoundé, Mokolo",
    },
    sourceData: {
      id: "KBO-7891",
      name: "Compteur Commercial",
      address: "45 Avenue Mokolo",
      type: "Triphasé",
      power: "30kVA",
    },
    targetData: {
      id: "ENEO-7891",
      name: "Compteur Commercial",
      address: "45 Avenue Mokolo",
      type: "Triphasé",
      power: "30kVA",
    },
    similarity: 98,
    confidence: 95,
  },
  {
    id: "task-006",
    type: "difference",
    status: "pending",
    priority: "high",
    title: "Écart de coordonnées GPS",
    description: "Position GPS différente de plus de 100m",
    createdAt: "2026-03-26T08:30:00Z",
    updatedAt: "2026-03-26T08:30:00Z",
    data: {
      koboId: "KBO-1122",
      eneoId: "ENEO-1122",
      location: "Garoua, Centre",
      distanceMeters: 156,
    },
  },
  {
    id: "task-007",
    type: "new_kobo",
    status: "in_progress",
    priority: "medium",
    title: "Lot de 12 nouveaux compteurs",
    description: "Import massif de données terrain",
    assignedTo: "5",
    createdAt: "2026-03-26T06:00:00Z",
    updatedAt: "2026-03-26T11:00:00Z",
    data: {
      batchId: "BATCH-2026-03-26",
      count: 12,
      region: "Nord",
    },
  },
  {
    id: "task-008",
    type: "duplicate",
    status: "completed",
    priority: "medium",
    title: "Doublon détecté - Zone Makepe",
    description: "Doublon potentiel à vérifier",
    assignedTo: "4",
    createdAt: "2026-03-26T07:30:00Z",
    updatedAt: "2026-03-26T10:30:00Z",
    completedAt: "2026-03-26T10:30:00Z",
    data: {
      koboId: "KBO-7892",
      eneoId: "ENEO-7892",
      location: "Douala, Makepe",
    },
    similarity: 85,
    confidence: 78,
  },
  {
    id: "task-009",
    type: "missing_eneo",
    status: "validated",
    priority: "high",
    title: "Point Eneo manquant - Quartier Bali",
    description: "Point référencé dans Eneo absent de Kobo",
    assignedTo: "6",
    createdAt: "2026-03-25T14:00:00Z",
    updatedAt: "2026-03-26T09:00:00Z",
    completedAt: "2026-03-26T08:00:00Z",
    validatedAt: "2026-03-26T09:00:00Z",
    validatedBy: "3",
    validationComment: "Point vérifié, intégration effectuée",
    data: {
      eneoId: "ENEO-6789",
      location: "Bamenda, Bali",
    },
    targetData: {
      id: "ENEO-6789",
      name: "Point Résidentiel",
      address: "12 Rue Bali",
      type: "Monophasé",
      power: "10kVA",
    },
  },
  {
    id: "task-010",
    type: "difference",
    status: "rejected",
    priority: "low",
    title: "Différence de consommation",
    description: "Écart de consommation anormal",
    assignedTo: "5",
    createdAt: "2026-03-25T16:00:00Z",
    updatedAt: "2026-03-26T07:00:00Z",
    completedAt: "2026-03-26T07:00:00Z",
    validatedAt: "2026-03-26T07:00:00Z",
    validatedBy: "3",
    validationComment: "Différence due à une maintenance programmée",
    data: {
      koboId: "KBO-3456",
      eneoId: "ENEO-3456",
      location: "Yaoundé, Nsam",
    },
  },
];

// Dashboard Statistics - Recalculées pour inclure les données du 26 mars
export const mockDashboardStats: DashboardStats = {
  totalTasks: 1085,
  pending: 238,
  inProgress: 159,
  completed: 688,
  validated: 613,
  rejected: 46,
  processingRate: 63.4,
  validationRate: 89.1,
  avgProcessingTime: 2.3,
};

// Agent Statistics - Mises à jour
export const mockAgentStats: AgentStats[] = [
  {
    userId: "4",
    user: mockUsers[3],
    tasksAssigned: 90,
    tasksCompleted: 82,
    tasksValidated: 76,
    tasksRejected: 6,
    occupancyRate: 90,
    avgProcessingTime: 1.7,
    efficiency: 93,
  },
  {
    userId: "5",
    user: mockUsers[4],
    tasksAssigned: 98,
    tasksCompleted: 71,
    tasksValidated: 63,
    tasksRejected: 8,
    occupancyRate: 71,
    avgProcessingTime: 2.8,
    efficiency: 89,
  },
  {
    userId: "3",
    user: mockUsers[2],
    tasksAssigned: 125,
    tasksCompleted: 113,
    tasksValidated: 113,
    tasksRejected: 0,
    occupancyRate: 75,
    avgProcessingTime: 1.1,
    efficiency: 100,
  },
  {
    userId: "6",
    user: mockUsers[5],
    tasksAssigned: 55,
    tasksCompleted: 53,
    tasksValidated: 51,
    tasksRejected: 2,
    occupancyRate: 55,
    avgProcessingTime: 1.3,
    efficiency: 96,
  },
];

// Weekly Trend - Mise à jour avec la semaine du 20 au 26 mars
export const mockWeeklyTrend: WeeklyTrend[] = [
  { date: "2026-03-20", completed: 42, validated: 38, rejected: 4 },
  { date: "2026-03-21", completed: 38, validated: 35, rejected: 3 },
  { date: "2026-03-22", completed: 45, validated: 42, rejected: 3 },
  { date: "2026-03-23", completed: 52, validated: 48, rejected: 4 },
  { date: "2026-03-24", completed: 48, validated: 45, rejected: 3 },
  { date: "2026-03-25", completed: 56, validated: 52, rejected: 4 },
  { date: "2026-03-26", completed: 44, validated: 41, rejected: 3 },
];

// Recent Activity - Activités du 26 mars
export const mockActivity: ActivityItem[] = [
  {
    id: "act-001",
    type: "task_validated",
    description: "Tâche #004 validée par Paul Mvondo",
    timestamp: "2026-03-26T08:00:00Z",
    userId: "3",
    user: mockUsers[2],
    taskId: "task-004",
  },
  {
    id: "act-002",
    type: "task_completed",
    description: "Traitement terminé - Doublon Zone Makepe",
    timestamp: "2026-03-26T10:30:00Z",
    userId: "4",
    user: mockUsers[3],
    taskId: "task-008",
  },
  {
    id: "act-003",
    type: "task_created",
    description: "Nouveau doublon détecté - Zone Mokolo",
    timestamp: "2026-03-26T10:00:00Z",
    taskId: "task-005",
  },
  {
    id: "act-004",
    type: "task_completed",
    description: "Traitement terminé - Nouvelle entrée Secteur 7",
    timestamp: "2026-03-26T09:30:00Z",
    userId: "4",
    user: mockUsers[3],
    taskId: "task-003",
  },
  {
    id: "act-005",
    type: "task_validated",
    description: "Tâche #009 validée - Point Bali",
    timestamp: "2026-03-26T09:00:00Z",
    userId: "3",
    user: mockUsers[2],
    taskId: "task-009",
  },
  {
    id: "act-006",
    type: "task_created",
    description: "Nouvelle tâche d'écart GPS",
    timestamp: "2026-03-26T08:30:00Z",
    taskId: "task-006",
  },
  {
    id: "act-007",
    type: "task_rejected",
    description: "Tâche #010 rejetée - Différence consommation",
    timestamp: "2026-03-26T07:00:00Z",
    userId: "3",
    user: mockUsers[2],
    taskId: "task-010",
  },
  {
    id: "act-008",
    type: "task_created",
    description: "Lot de 12 nouveaux compteurs - Région Nord",
    timestamp: "2026-03-26T06:00:00Z",
    taskId: "task-007",
  },
  {
    id: "act-009",
    type: "task_created",
    description: "Doublon détecté - Compteur #A2345",
    timestamp: "2026-03-26T08:00:00Z",
    taskId: "task-001",
  },
  {
    id: "act-010",
    type: "task_in_progress",
    description: "Traitement en cours - Différence Bonanjo",
    timestamp: "2026-03-26T10:15:00Z",
    userId: "5",
    user: mockUsers[4],
    taskId: "task-002",
  },
];

// GeoPoints for Map
export const mockGeoPoints: GeoPoint[] = [
  { id: "geo-001", lat: 3.8480, lng: 11.5021, type: "kobo", status: "completed", data: { name: "Point A - Mvan" } },
  { id: "geo-002", lat: 3.8550, lng: 11.5150, type: "eneo", status: "validated", data: { name: "Point B - Bastos" } },
  { id: "geo-003", lat: 3.8600, lng: 11.4900, type: "processed", status: "in_progress", data: { name: "Point C - Mokolo" } },
  { id: "geo-004", lat: 4.0511, lng: 9.7679, type: "kobo", status: "pending", data: { name: "Point D - Bonanjo" } },
  { id: "geo-005", lat: 4.0600, lng: 9.7800, type: "eneo", status: "completed", data: { name: "Point E - Makepe" } },
  { id: "geo-006", lat: 4.0450, lng: 9.7550, type: "kobo", status: "validated", data: { name: "Point F - Akwa" } },
  { id: "geo-007", lat: 5.9631, lng: 10.1591, type: "processed", status: "completed", data: { name: "Point G - Bali" } },
  { id: "geo-008", lat: 9.3265, lng: 13.3972, type: "kobo", status: "pending", data: { name: "Point H - Garoua" } },
  { id: "geo-009", lat: 3.8420, lng: 11.5080, type: "kobo", status: "pending", data: { name: "Point I - Nouveau" } },
  { id: "geo-010", lat: 4.0550, lng: 9.7750, type: "eneo", status: "pending", data: { name: "Point J - Nouveau" } },
];

// Regions
export const mockRegions: Region[] = [
  { id: "reg-001", name: "Centre", code: "CE", pointsCount: 465, completionRate: 79 },
  { id: "reg-002", name: "Littoral", code: "LT", pointsCount: 532, completionRate: 86 },
  { id: "reg-003", name: "Ouest", code: "OU", pointsCount: 318, completionRate: 63 },
  { id: "reg-004", name: "Nord", code: "NO", pointsCount: 201, completionRate: 48 },
  { id: "reg-005", name: "Sud", code: "SU", pointsCount: 148, completionRate: 72 },
  { id: "reg-006", name: "Est", code: "ES", pointsCount: 102, completionRate: 56 },
  { id: "reg-007", name: "Adamaoua", code: "AD", pointsCount: 91, completionRate: 49 },
  { id: "reg-008", name: "Nord-Ouest", code: "NW", pointsCount: 138, completionRate: 59 },
  { id: "reg-009", name: "Sud-Ouest", code: "SW", pointsCount: 171, completionRate: 68 },
  { id: "reg-010", name: "Extrême-Nord", code: "EN", pointsCount: 142, completionRate: 44 },
];

// Notifications - Mises à jour
export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    type: "new_task",
    title: "Nouvelle tâche assignée",
    message: "Un nouveau doublon a été détecté et vous a été assigné - Zone Mokolo",
    isRead: false,
    createdAt: "2026-03-26T10:00:00Z",
    linkTo: "/processing/duplicates/task-005",
  },
  {
    id: "notif-002",
    type: "task_validated",
    title: "Tâche validée",
    message: "Votre traitement #004 a été validé par Paul Mvondo",
    isRead: false,
    createdAt: "2026-03-26T08:00:00Z",
    linkTo: "/validation/task-004",
  },
  {
    id: "notif-003",
    type: "task_completed",
    title: "Tâche complétée",
    message: "Votre tâche #008 a été marquée comme complétée",
    isRead: false,
    createdAt: "2026-03-26T10:30:00Z",
    linkTo: "/processing/task-008",
  },
  {
    id: "notif-004",
    type: "task_validated",
    title: "Validation effectuée",
    message: "La tâche #009 a été validée avec succès",
    isRead: false,
    createdAt: "2026-03-26T09:00:00Z",
    linkTo: "/validation/task-009",
  },
  {
    id: "notif-005",
    type: "task_rejected",
    title: "Tâche rejetée",
    message: "Le traitement #010 a été rejeté. Veuillez vérifier les commentaires.",
    isRead: true,
    createdAt: "2026-03-26T07:00:00Z",
    linkTo: "/validation/task-010",
  },
];

// Electric Regions (ENEO Organization)
export const mockElectricRegions: ElectricRegion[] = [
  { id: "er-001", name: "Région Électrique Douala Ouest", code: "RDUO", city: "Douala" },
  { id: "er-002", name: "Région Électrique Douala Est", code: "RDUE", city: "Douala" },
  { id: "er-003", name: "Région Électrique Douala Centre", code: "RDUC", city: "Douala" },
  { id: "er-004", name: "Région Électrique Yaoundé Nord", code: "RYN", city: "Yaoundé" },
  { id: "er-005", name: "Région Électrique Yaoundé Sud", code: "RYS", city: "Yaoundé" },
  { id: "er-006", name: "Région Électrique Yaoundé Centre", code: "RYC", city: "Yaoundé" },
  { id: "er-007", name: "Région Électrique Garoua", code: "RG", city: "Garoua" },
  { id: "er-008", name: "Région Électrique Bamenda", code: "RB", city: "Bamenda" },
  { id: "er-009", name: "Région Électrique Buea", code: "RBU", city: "Buea" },
  { id: "er-010", name: "Région Électrique Bertoua", code: "RBE", city: "Bertoua" },
];

// Task Stats by Region
export const mockTaskStatsByRegion: TaskStatsByRegion[] = [
  {
    region: mockElectricRegions[0],
    totalTasks: 238,
    pending: 46,
    inProgress: 29,
    completed: 147,
    validated: 142,
    rejected: 16,
    completionRate: 63,
  },
  {
    region: mockElectricRegions[1],
    totalTasks: 202,
    pending: 33,
    inProgress: 26,
    completed: 130,
    validated: 124,
    rejected: 13,
    completionRate: 66,
  },
  {
    region: mockElectricRegions[2],
    totalTasks: 171,
    pending: 29,
    inProgress: 19,
    completed: 114,
    validated: 110,
    rejected: 9,
    completionRate: 68,
  },
  {
    region: mockElectricRegions[3],
    totalTasks: 249,
    pending: 53,
    inProgress: 36,
    completed: 150,
    validated: 144,
    rejected: 10,
    completionRate: 61,
  },
  {
    region: mockElectricRegions[4],
    totalTasks: 216,
    pending: 39,
    inProgress: 23,
    completed: 139,
    validated: 134,
    rejected: 15,
    completionRate: 66,
  },
];

// Task Stats by City
export const mockTaskStatsByCity: TaskStatsByCity[] = [
  {
    city: "Douala",
    regions: mockElectricRegions.slice(0, 3),
    totalTasks: 611,
    pending: 108,
    completionRate: 66,
  },
  {
    city: "Yaoundé",
    regions: mockElectricRegions.slice(3, 6),
    totalTasks: 522,
    pending: 95,
    completionRate: 64,
  },
  {
    city: "Garoua",
    regions: [mockElectricRegions[6]],
    totalTasks: 159,
    pending: 29,
    completionRate: 59,
  },
  {
    city: "Bamenda",
    regions: [mockElectricRegions[7]],
    totalTasks: 138,
    pending: 25,
    completionRate: 62,
  },
];

// Task Stats by Zone
export const mockTaskStatsByZone: TaskStatsByZone[] = [
  { zone: "Zone Résidentielle Nord", totalTasks: 238, completed: 149 },
  { zone: "Zone Commerciale", totalTasks: 192, completed: 132 },
  { zone: "Zone Industrielle", totalTasks: 158, completed: 95 },
  { zone: "Zone Administrative", totalTasks: 101, completed: 70 },
  { zone: "Zone Rurale", totalTasks: 148, completed: 81 },
];

// Task Stats by Exploitation
export const mockTaskStatsByExploitation: TaskStatsByExploitation[] = [
  { exploitationId: "exp-001", exploitationName: "Exploitation Douala Centre", totalTasks: 131, completed: 92, avgProcessingTime: 2.0 },
  { exploitationId: "exp-002", exploitationName: "Exploitation Douala Ouest", totalTasks: 115, completed: 81, avgProcessingTime: 1.8 },
  { exploitationId: "exp-003", exploitationName: "Exploitation Yaoundé Nord", totalTasks: 148, completed: 101, avgProcessingTime: 2.2 },
  { exploitationId: "exp-004", exploitationName: "Exploitation Yaoundé Centre", totalTasks: 137, completed: 95, avgProcessingTime: 1.9 },
  { exploitationId: "exp-005", exploitationName: "Exploitation Garoua", totalTasks: 89, completed: 54, avgProcessingTime: 2.7 },
];